### ISSUE TITLE
Todo al ToDo - Gabri

### ISSUE THREAD

**Issue by webbri** [webreactiva-devs/reto-nextjs#2]
# Todo al ToDo (Reto Next JS Web Reactiva)

**Estado**: Me faltan por pulir algunos detalles (sobretodo estéticos), pero los requisitos básicos están y es funcional.

## Acceso y código del reto

👉[URL del repo en GitHub](https://github.com/gabrim90/webreactiva-retonextjs)
👉[Aplicación en Vercel](https://webreactiva-retonextjs.vercel.app/)

## Descripción
**Todo al ToDo** es una pequeña aplicación en la que el ChatGPT te sugiere listas de tareas. Por ejemplo _¿Cómo hacer una tortilla de patata con cebolla?_ . El Chatbot GPT devovlerá un listado de puntos y se presentan en forma de lista. Las listas se pueden guardar dándoles un nombre y también consultar las que han hecho los otros usuarios.

## Funcionalidad
Para [acceder](https://webreactiva-retonextjs.vercel.app) introducimos un correo y **nos llegará un email de acceso**. Hacemos click en el enlace y nos cargará la [pantalla principal](https://webreactiva-retonextjs.vercel.app/). En [Crear ToDo](https://webreactiva-retonextjs.vercel.app/create) podemos hacer la consulta al ChatGTP para que nos sugiera lista de tareas. Hay que esperar un poco, porque **tarda en responder**. En [Mis listas creadas](https://webreactiva-retonextjs.vercel.app/lists) se pueden ver las listas creadas para el usuario actual. Si hacemos click en una ([ejemplo](https://webreactiva-retonextjs.vercel.app/lists/18)) podemos ver el detalle. En la parte derecha siempre tenemos todas las listas que se han ido creando **por todos los usuarios**.

## Tecnologías utilizadas
- React
- NextJs (versión 13)
- TailwindCSS
- Supabase

## Por hacer:
- [ ] Mejoras estéticas y visuales
- [ ] Mejorar el proceso del login y poner el mensaje de que se ha enviado el email de acceso
- [ ] Poner gifs de cargando 
- [ ] Marcar mejor los enlaces
